name: Cross-Compile Project for Windows

on: 
  workflow_dispatch:
    inputs:
      desc:
        type: string
        description: "Description for new release"
        required: true
        default: 'New Test Release'
  push:
    branches:
      - master

jobs:
  cross_compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MXE dependencies and cross-compiler
      run: |
        git clone https://github.com/mxe/mxe.git
        cd mxe
        MXE_GCC_THREADS=posix \
        MXE_PLUGIN_DIRS=plugins/gcc6/ \
        make libiconv zlib libpng jpeg boost openssl libwebp -j8 JOBS=8
        cd ..

    - name: Create MXE build directory
      run: mkdir build-mxe

    - name: Configure and cross-compile project for Windows
      run: |
        cd build-mxe
        ../mxe/usr/bin/i686-w64-mingw32.static-cmake ..
        make -j8

    - name: List cross-compiled executables
      run: ls build-mxe/
